# -*- coding: utf-8 -*-
"""bag of n-grams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SN4sVw_I0JIHmiN1LolircGwNuGq45oc
"""

from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

v = CountVectorizer(ngram_range=(1, 2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

v = CountVectorizer(ngram_range=(1, 3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

import spacy

# Load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
  # remove stop words and lemmatize the text
  doc = nlp(text)
  filtered_tokens = []
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)
  return " ".join(filtered_tokens)

preprocess("Thor ate pizza")

preprocess("Loki is eating pizza")

corpus_preprocessed = [preprocess(text) for text in corpus]
print(corpus_preprocessed)

v = CountVectorizer(ngram_range=(1, 2))
v.fit(corpus_preprocessed)
v.vocabulary_

v.transform(["Thor eat pizza"]).toarray()

v.transform(["Hulk eat pizza"]).toarray()

"""**Task:**

Use bag of n-grams for new category classification problem and train a mchine learning model that can categorize any news into one of folowing categories.



*   Business
*   Sports
*   Crime
*  Science


**Dataset**

Dataset Credits: https://www.kaggle.com/code/hengzheng/news-category-classifier-val-acc-0-65

"""

import pandas as pd

df = pd.read_json("/content/news_dataset.json")
print(df.shape)

df.head()

df.category.value_counts()

"""Balancing data"""

min_sample = 1381

df_business = df[df.category == "BUSINESS"].sample(min_sample, random_state=2022)
df_sport = df[df.category == "SPORTS"].sample(min_sample, random_state=2022)
df_crime = df[df.category == "CRIME"].sample(min_sample, random_state=2022)
df_science = df[df.category == "SCIENCE"].sample(min_sample, random_state=2022)

df_balanced = pd.concat([df_business, df_sport, df_crime, df_science], axis=0)
df_balanced.category.value_counts()

"""Convert text category to a number"""

target = {'BUSINESS': 0, 'SPORT': 1, 'CRIME': 2, 'SCIENCE': 3}

df_balanced['category_num'] = df_balanced['category'].map({
    'BUSINESS': 0,
    'SPORTS': 1,
    'CRIME': 2,
    'SCIENCE': 3
})

df_balanced.head()

"""Build a model with original text(no pre processing)"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_balanced.text,
    df_balanced.category_num,
    test_size=0.2,
    stratify=df_balanced.category_num
    )

print("Train dataset shape:", X_train.shape)
print("\nTetst dataset shape:", X_test.shape)
X_train.head()

print(y_train.value_counts())
print(f"\n{y_test.value_counts()}")

from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf = Pipeline([
    ('vectorizer_bow', CountVectorizer()),
    ('Multi NB', MultinomialNB())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

print(X_test[:5])
print(y_pred[:5])

"""Using 1-gram and bigrams"""

# Create a pipeline object
clf = Pipeline([
    ('vectorizer_bow', CountVectorizer(ngram_range=(1, 2))),
    ('Multi NB', MultinomialNB())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classfication report
print(classification_report(y_test, y_pred))

"""Use 1-gram to trigrams"""

# create a pipeline obl=ject
clf = Pipeline([
    ('vectorizer_bow', CountVectorizer(ngram_range=(1, 2))),
    ('Multi NB', MultinomialNB())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classification report
print(classification_report(y_test, y_pred))

"""Use text preprocessing to remove stop wprds, punctuations and apply lemmatization"""

df_balanced['preprocessed_text'] = df_balanced['text'].apply(preprocess)
df_balanced.head()

# train/test
X_train, X_test, y_train, y_test = train_test_split(
    df_balanced.preprocessed_text,
    df_balanced.category_num,
    test_size=0.2,
    stratify=df_balanced.category_num
    )
print(X_train.shape)
print(X_test.shape)

y_train.value_counts()

# Create a pipeline object
clf = Pipeline([
    ('vectorizer_bow', CountVectorizer(ngram_range=(1, 2))),
    ('Multi NB', MultinomialNB())
])

# fit with X_train and y_train]
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classification report
print(classification_report(y_test, y_pred))

"""Plot confusion matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(5, 5))

# Get unique category names from df_balanced for xticklabels and yticklabels
target_names = df_balanced['category'].unique()

sns.heatmap(cm, annot=True, fmt='g', vmin=0, cmap='Blues', cbar=False,
            xticklabels=target_names, yticklabels=target_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")