# -*- coding: utf-8 -*-
"""emotion_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQ5gr1GMt_HhHH5Z8qGP0_cUObiSyXrA
"""

import pandas as pd

df = pd.read_csv("/content/Emotion_classify_Data.csv")

print(df.shape)

df.head()

#che ck distribution of emotions
emt_dist = df['Emotion'].value_counts()
print(emt_dist)

df['Emotion_num'] = df['Emotion'].map({
    'anger':0,
    'joy':1,
    'fear':2
})
df.head()

"""modeling without pre-processing text data"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Comment'],
                                                    df['Emotion_num'],
                                                    test_size=0.2,
                                                    random_state=2022,
                                                    stratify=df['Emotion_num']
                                                    )
print("Shape of X_train :", X_train.shape)
print("Shape of X_test :", X_test.shape)
print("\nNumber of training samples :", y_train.shape[0])
print("Number of testing samples :", y_test.shape[0])

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf_rf = Pipeline([
    ('vectorizer_count', CountVectorizer(ngram_range=(3,3))),
    ('random_forest', (RandomForestClassifier()))
])

clf_rf.fit(X_train, y_train)

y_pred = clf_rf.predict(X_test)
print(classification_report(y_test, y_pred))

clf_mnb = Pipeline([
    ('vectorizer_count', CountVectorizer(ngram_range=(1,2))),
    ('multinomial_nb', (MultinomialNB()))
])

clf_mnb.fit(X_train, y_train)

y_pred = clf_mnb.predict(X_test)
print(classification_report(y_test, y_pred))

clf_rf = Pipeline([
    ('vectorizer_count', CountVectorizer(ngram_range=(1,2))),
    ('random_forest', (RandomForestClassifier()))
])

clf_rf.fit(X_train, y_train)

y_pred = clf_rf.predict(X_test)

print(classification_report(y_test, y_pred))

from sklearn.feature_extraction.text import TfidfVectorizer

clf_rf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('random_forest', (RandomForestClassifier()))
])
clf_rf.fit(X_train, y_train)

y_pred = clf_rf.predict(X_test)
print(classification_report(y_test, y_pred))

"""Use text pre-processing to remove stop words, punctuations and apply lemmatization"""

import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm")

#use this utility function to get the preprocessed text data
def preprocess(text):

  #remove stpo words and lemmatize the text
  doc = nlp(text)
  filtered_tokens = []
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)

  return " ".join(filtered_tokens)

# create a new column "preprocessed_comment" and use the utility function above to get the clean data
df['Preprocessed_Comment'] = df['Comment'].apply(preprocess)
df.head()

"""build a model with pre-processed text"""

X_train, X_test, y_train, y_test = train_test_split(df['Preprocessed_Comment'],
                                                    df['Emotion_num'],
                                                    test_size=0.2,
                                                    random_state=2022,
                                                    stratify=df['Emotion_num']
                                                    )
print("Shape of X_train :", X_train.shape)
print("Shape of X_test :", X_test.shape)
print("\nNumber of training samples :", y_train.shape[0])
print("Number of testing samples :", y_test.shape[0])

clf_rf = Pipeline([
    ("countvectorizer", CountVectorizer(ngram_range=(1,2))),
    ('random_forest', (RandomForestClassifier()))
])

clf_rf.fit(X_train, y_train)

y_pred = clf_rf.predict(X_test)
print(classification_report(y_test, y_pred))

clf_rf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('random_forest', (RandomForestClassifier()))
])

clf_rf.fit(X_train, y_train)

y_pred = clf_rf.predict(X_test)
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

import matplotlib.pyplot as plt
import seaborn as sns
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel("Predicted")
plt.ylabel("Truth")