# -*- coding: utf-8 -*-
"""Fake News Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aknk0n0a6tnsE1hW0OIPzmD299Nvtv1m

**Task:**

* Use classical NLP
techniques to classify whether a given message/text is **Real or Fake
Message.**

* Use Bag of n-grams to preprocess the next and apply different classification algorithms.

* Scikit-learn CountVectorizert.

Credits: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/Fake_Real_Data.csv")

print("dataset shape:", df.shape)
df.head()

# check distribution of labels

df.label.value_counts()

#Add the new column "label_num" which gives a unique number to each of these labels
df['label_num'] = df.label.map({'Real': 1, 'Fake': 0})
df.head()

"""Modelling without preprocess Text data"""

from sklearn.model_selection import train_test_split

# Do the "train-test" splitting with test size of 20% with random state of 2022 and stratify sampling too
X_train, X_test, y_train, y_test = train_test_split(
    df.Text, # Changed to df.Text for features
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num,
)
print("Shape of X_train is:", X_train.shape)
print("\nShape of X_test is:", X_test.shape)

"""Use scikit-learn pipeline module to create a classification pipeline to classify the data."""

from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer # Corrected import
from sklearn.neighbors import KNeighborsClassifier

# create a pipeline object
clf = Pipeline([
    ("Count-vetorzer", CountVectorizer()), # Corrected class name
    ("KNN", KNeighborsClassifier())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classfication report
print(classification_report(y_test, y_pred))

"""**Use:**
* CountVectorizer with only trigrams.
* RandomForest as the classifier
* Print the classification report
"""

from sklearn.ensemble import RandomForestClassifier
# create a pipeline object
clf = Pipeline([
    ("Count-vetorzer", CountVectorizer(ngram_range=(3,3))), # Corrected class name
    ("RF", RandomForestClassifier())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it y_pred
y_pred = clf.predict(X_test)


# print the classfication report
print(classification_report(y_test, y_pred))

"""**Use:**
* CountVectorizer with both unigram and bigrams.
* Multinomial Naive Bayes as the classifier with
"""

from sklearn.naive_bayes import MultinomialNB
# create a pipeline object
clf = Pipeline([
    ("Count-vetorzer", CountVectorizer(ngram_range=(1,2))), # Corrected class name
    ("MNB", MultinomialNB())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classfication report
print(classification_report(y_test, y_pred))

"""**Use:**
* CountVectorizer with unigram, Bigram, and trigrams
* RandomForest as the classifier.
* print a classification report
"""

# create a pipeline object
clf = Pipeline([
    ("count-vectorizer", CountVectorizer()),
    ("RF", RandomForestClassifier())
])

# fit with X_train and y_train
clf.fit(X_train, y_train)

# get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)

# print the classification report
print(classification_report(y_test, y_pred))

# Pirnt the confusion matrix for the best model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

plt.figure(figsize=(10,6))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')