# -*- coding: utf-8 -*-
"""stopwords_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2ibbRc0jBNzRvGqfiyLcdNfEmLrEKjr
"""

# Import spacy and loading the modeel

import spacy
nlp = spacy.load("en_core_web_sm")

"""**Task1:**


*   From a given text, count the number of stop words in it.
* Print the percentage of stop word tokens compared to all tokens in a given text.


"""

text = '''
Thor: Love and Thunder is a 2022 American superhero film based on Marvel Comics featuring the character Thor, produced by Marvel Studios and
distributed by Walt Disney Studios Motion Pictures. It is the sequel to Thor: Ragnarok (2017) and the 29th film in the Marvel Cinematic Universe (MCU).
The film is directed by Taika Waititi, who co-wrote the script with Jennifer Kaytin Robinson, and stars Chris Hemsworth as Thor alongside Christian Bale, Tessa Thompson,
Jaimie Alexander, Waititi, Russell Crowe, and Natalie Portman. In the film, Thor attempts to find inner peace, but must return to action and recruit Valkyrie (Thompson),
Korg (Waititi), and Jane Foster (Portman)—who is now the Mighty Thor—to stop Gorr the God Butcher (Bale) from eliminating all gods.
'''


# Create the object 'doc' for the given text using nlp()
doc = nlp(text)

# Define the variables to keep track of stopwords count and total words count
stop_words_count = 0
total_words_count = 0

# Iterate through all the words in the document
for token in doc:
  if token.is_stop:  # check whether given token is stop word or not and increment accordingly
    stop_words_count += 1
  total_words_count += 1 # increment the total_words_count

# Print the count of stop words
print("Stop words count:", stop_words_count)

# Print the percentage of stop words compared to total words in the text
print("Percentage of stop words:", f"{(stop_words_count/total_words_count)*100}%")

"""**Task2:**


*   From a given text, output the most frequently used token after removing all the stop word tokens and punctuations in it.


"""

text = '''
The India men's national cricket team, also known as Team India or the Men in Blue, represents India in men's international cricket.
It is governed by the Board of Control for Cricket in India (BCCI), and is a Full Member of the International Cricket Council (ICC) with Test,
One Day International (ODI) and Twenty20 International (T20I) status. Cricket was introduced to India by British sailors in the 18th century, and the
first cricket club was established in 1792. India's national cricket team played its first Test match on 25 June 1932 at Lord's, becoming the sixth team to be
granted test cricket status.
'''

# Create the object 'doc' for the given text using nlp()
doc = nlp(text)
remaining_tokens = []
for token in doc:
  if not (token.is_stop or token.is_punct): # check whether a given token is stop word or punctuations
    remaining_tokens.append(token.text)

# Create a new  dictionary and get the frequency of words by iterating  through the list which contains stored tokens
frequency_tokens = {}
for token in remaining_tokens:
  if token != '\n' and token != ' ': # As spacy considers new line and empty spaces as seperate token, it's better to ignore them
    if token not in frequency_tokens: # if a particular token occurs for the first time, we initiate it to 1
      frequency_tokens[token] = 1
    else:
      frequency_tokens[token] += 1  #if a particular token is already present,. then increment by 1 based on value already presented

# Get the maximum frequency word
max_freq_word = max(frequency_tokens.keys(), key=(lambda key: frequency_tokens[key]))

# Print the maximum frequency word
print(f"The most frequently used token after removing all the stop word tokens and punctuations in it: {max_freq_word}")