# -*- coding: utf-8 -*-
"""Stop words

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjSB54P7ftKsUSFLlKKQy0NHpC4Fk6y7
"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

# Sample text
text = "This is a sample sentence showing stpword removal."

# Get English stopwords and tokenize
stop_words = set(stopwords.words("english"))
tokens = word_tokenize(text.lower())

# Remove stopwords
filtered_tokens = [word for word in tokens if word not in stop_words]

print("Original:", tokens)
print("Filtered:", filtered_tokens)

"""Implementation using Spacy"""

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("The reseachers are developing advanced algorithms.")

#Fliter stopwords using spaCy
filtered_words = [token.text  for token in doc if not token.is_stop]
print("Filtered:", filtered_words)

"""Removing stop words with Genism"""

!pip install gensim
from gensim.parsing.preprocessing import remove_stopwords

# Another sample text
new_text = "The majestic mountains provides a breathtaking view."

new_filtered_text = remove_stopwords(new_text)

print("\nOriginal Text:", new_text)
print("\nText after Stopword Removal:", new_filtered_text)

"""Implementation with Scikit Learn"""

from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Another sample text
new_text = "The quick brown fox jumps over the lazy dog."

# Remove stopwords using NLTK
new_filtered_words = [word for word in word_tokenize(new_text.lower()) if word not in stopwords.words("english")]

# Join the filtered words to from a clean text
new_clean_text = " ".join(new_filtered_words)

print("\nOriginal Text:", new_text)
print("\nText after stopwords removal:", new_filtered_words)
print("\nOriginal Text:", new_text)
print("\nText after Stopword Removal:", new_clean_text)

"""Custom Stopwords for Real-world applications tailord to specific domains:"""

from collections import Counter

def create_custom_stopwords(texts, threshold=0.1):
  # Count word frequencies across all texts
  all_words = []
  for text in texts:
    words = text.split()
    all_words.extend(words)

  word_freq = Counter(all_words)
  total_words = len(all_words)

  # Words appearing more than threshold become stopwords

  custom_stops = {words for word, freq in word_freq.items()
  if freq / total_words > threshold}

  return custom_stops.union(set(stopwords.words('english')))