# -*- coding: utf-8 -*-
"""TF-IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UfTKkripSQQXURC-jx_XoR-xqE2lGJu
"""

from sklearn.feature_extraction.text import TfidfVectorizer

corpus =[
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

# Create the vectorizer and fit the corpus and transform them accordingly
v = TfidfVectorizer()
v.fit(corpus)
transform_output = v.transform(corpus)

print(v.vocabulary_)

# print the idf of each word

all_feature_names = v.get_feature_names_out()

for word in all_feature_names:
  #Let's get the index in the vocabulary
    indx = v.vocabulary_.get(word)

    #get the score
    idf_score = v.idf_[indx]

    print(f"{word}:{idf_score}")

# convert the transformed output from tf-idf to an array and the print
print(transform_output.toarray())

import pandas as pd

# read the data into padnas dataframe
df = pd.read_csv("/content/Ecommerce_data.csv")
print(df.shape)
df.head(5)

#check the dribution of label
print(df['label'].value_counts())

import matplotlib.pyplot as plt
plt.pie(df['label'].value_counts(), labels=['Household', 'Books', 'Electronics', 'Clothing & Accessories'], autopct="%0.2f")
plt.show()

#Adding a new column which gives a unique number to each of these labels

df['label_num'] = df['label'].map({
    'Household':0,
    'Books':1,
    'Electronics':2,
    'Clothing & Accessories':3
})

df.head()

#creating a model with the original text withou preprocessing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.label,
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num
)
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

print("X_train number of values:", X_train.value_counts())
print("\nX_test number of values:", X_test.value_counts())
print("\ny_train number of values:", y_train.value_counts())
print("\ny_test number of values:", y_test.value_counts())

from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

# create a pipeline object
clf = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('knn', KNeighborsClassifier())
])

# fit with training data
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

X_test[:5]

y_test[:5]

# using MultinomialNB classifier
from sklearn.naive_bayes import MultinomialNB

# create a pipeline object
clf = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('nb', MultinomialNB())
])

# fit with training data
clf.fit(X_train, y_train)

# get the predictions for test data
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

#using random forest classifier
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('rf', RandomForestClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

"""Use text pre-processing to remove stop words punctuations and apply lemmatization"""

import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm")

# create a utility function for pre-processing the text
def preprocess(text):
  # remove stop words and lemmatize the text
  doc = nlp(text)
  filtered_tokens = []
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)

  return " ".join(filtered_tokens)

# create new column for the pre-processed text
df['preprocessed_txt'] = df['Text'].apply(preprocess)
df.head()

df.Text[0]

df.preprocessed_txt[0]

X_train, X_test, y_train, y_test = train_test_split(
    df.preprocessed_txt,
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num
)

clf = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('rf', RandomForestClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize=(10,6))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')